### ISSUE TITLE
Url Validierung kann umgangen werden & Fehler in URL Handling

### ISSUE THREAD

**Issue by AstroGD** [DeepRobin/deep-shortener#14]
Die Url Validierung ist Clientseitig, kann also deaktiviert werden.
Dadurch sind nicht existierende Urls möglich.

Es wäre sinnvoll, eine URL Validierung auf dem Server einzubauen, da diese nicht vom Client verändert werden kann.

Beispiel: https://shrt.deeprobin.de/AILgs
Ebenso ist es so möglich bestimmte Codesnippets einzufügen, welche nicht gecacht werden. Dies ist also ein weiterer Fehler.

Beispiel: https://shrt.deeprobin.de/2TSKv

Ich habe bis jetzt nicht herausfinden können ob dadurch eine COde Injection Attack möglich ist.
Da dies aber sein kann sollte der Fehler asap gefixt werden.

**Comment by deeprobin** [comment]
Ja das stimmt. Ich werde noch einen zusätzlichen Check serverseitig einbauen

**Comment by deeprobin** [comment]
Eine Code Injection Attack ist aber trotzdem meines Erachtens nach nicht möglich, weil das wird ja nicht evaluiert. Ist ja nur lowdb
