### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by rizecookey** [DeepRobin/deep-shortener#5]
https link shows invalid certificate in chrome (probably in other browser as well)

accessing the website with http opens the default nginx page

**Comment by rizecookey** [comment]
accessing the website in firefox over https seems to work (after ignoring invalid certificate)
trying to ignore the certificate warning in chrome does not work

**Comment by rizecookey** [comment]
submit button is broken in firefox

**Comment by deeprobin** [comment]
The broken submit button was already fixed in pr #3 

But the server isn't up to dte

**Comment by deeprobin** [comment]
All this bugs are now fixed.
